apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "headless-service.appName" . }}
subsets:
- addresses:
  - ip: {{ include "headless-service.ipAddress" . }}
  ports:
  - name: app
    port: {{ include "headless-service.servicePort" . }}
    protocol: TCP
