apiVersion: v1
kind: Service
metadata:
  name: {{ include "headless-service.appName" . }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: app
      port: 80
      protocol: TCP
      targetPort: {{ include "headless-service.servicePort" . }}
